### ISSUE TITLE
remove "require 'byebug'"

### ISSUE THREAD

**Issue by littldr** [jannishuebl/orchparty#12]
As `byebug` is not specified as dependency in the `gemspec` you should avoid adding `require 'byebug'` (see: [here](https://github.com/jannishuebl/orchparty/blob/9cf3d6a862cad9f65499043cc28340caffd932e5/lib/orchparty/transformations/mixin.rb#L1)) in your code. If `byebug` is not installed it will raise an exception. :)

If you want to use `byebug` while developing simply add `require 'byebug'` in `bin/console` before `IRB.start`. With this change, you can use `bin/console` as an entrypoint for debugging the code. :)

**Comment by jannishuebl** [comment]
Thank you for the reference  :)

I will Implement it like you suggested :+1:
