### ISSUE TITLE
"network" needed in application 

### ISSUE THREAD

**Issue by pschrammel** [jannishuebl/orchparty#13]
I'm getting 
error: undefined method `deep_transform_values' for nil:NilClass
/home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/orchparty-1.0.0/lib/orchparty/plugins/docker_compose_v2.rb:24:in `transform_to_yaml': undefined method `deep_transform_values' for nil:NilClass (NoMethodError)
	from /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/orchparty-1.0.0/lib/orchparty/plugins/docker_compose_v2.rb:36:in `output'
	from /home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/orchparty-1.0.0/lib/orchparty/plugins/docker_compose_v2.rb:15:in `generate'

if I'm not defining a network block in application

**Comment by jannishuebl** [comment]
fixed with v1.0.1
