### ISSUE TITLE
empty mixins in all cause errors

### ISSUE THREAD

**Issue by pschrammel** [jannishuebl/orchparty#15]
If you have an empty mixin and mix it into all an error is thrown, this code throws an error in 1.0.1:

```
application 'testapp' do
  all do
    mix 'dev'
    image -> { image }
  end
  variables do
    var image: 'test/test'
  end  
  mixin 'dev' do
  end
  service 'test' do
  end
end
```

**Comment by pschrammel** [comment]
the current workaround is to define some variable in the dev mixin.

**Comment by jannishuebl** [comment]
I'll add default values so that should not happen anymore
