### ISSUE TITLE
Make it possible to call a method multiple times inside of service

### ISSUE THREAD

**Issue by florin555** [jannishuebl/orchparty#21]
I see that for example if I call "environment" two times in a service, only the last call is "registered". Would it be possible to make it so that it picks up both calls (merge their content, how it behaves when calling envirnoment both in mixin and in service)?
My use-case is that I want to add some environment variables always, and then add a few more from inside an "if".

**Comment by jannishuebl** [comment]
Hey,
 
I think this is possible, hope to implement this next week. 

cheers

jannis
